name: ping_discover_network_plus
description: Library that allows to ping IP subnet and discover network devices. Could be used to find printers and other devices and services in a local network.
version: 0.0.3
homepage: https://github.com/brasizza/ping_discover_network

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  wifi_info_plugin_plus: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
